title: amaruak00 blog
author: amaruak00
email: amaruak00@hanwha.com
description: > # this means to ignore newlines until "show_exerpts:"
  South Korea. Hanwha Systems. Data Scientist. AI Developer.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
url: "https://amaruak00.github.io/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: amaruak00
  tagline: Seeing much. Suffering much. Studying much.
  date_format: "%Y.%b.%-d"
  style: red 
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  amaruak00
    linkedIn: in/amaruak00
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
